### ISSUE TITLE
You should multiply p12_nonMoyenne and p13_nonMoyenne by length(vecx)

### ISSUE THREAD

**Issue by thaos** [PaulaFlorencia/codegithub#1]
https://github.com/PaulaFlorencia/codegithub/blob/2108127ff0b42ac183595d05bb4d474213158370/p.R#L858-L863

You should multiply p12_nonMoyenne and p13_nonMoyenne by length(vecx) because it is gmm who compute the mean/the expected value  afterwards, that is it does mean( p12_nonMoyenne - p12val). But in the case of kernel smoothing, to have the expected value we should do sum( p12_nonMoyenne - p12val) = sum(W*vecx - p12val) instead. So to compensate we have to multiply by length(vecx),

**Comment by PaulaFlorencia** [comment]
Oh I see , thanks.
